[package]
edition = "2021"
name = "wod"
version = "0.1.0"
authors = ["Orien Vandenbergh <orien.vandenbergh@defpoint.com>"]

[dependencies]
reqwest = "0.11.22"
futures = "0.3.0"
scraper = "0.18.1"
select = "0.6.0"
tokio = { version = "1.12.0", features = ["full"] }
